config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :articles do
    resources :votes, only: [:create, :destroy]
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :votes

	validates :title, presence: true
	validates :description, presence: true

	def blurb
		description = self.description
		blurb = description.truncate(200, separator: /\s/)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
	has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :set_voter
  before_filter :set_allowed_voting_groups

  def set_voter
  	@voter = User.find(3)
  	@logged_in_user = User.find(3)
  end
  def set_allowed_voting_groups
    @allowed_voting_groups = ["authors", "voters"]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  	@articles = Article.all
  end

  def show
  	@article = Article.find(params[:id])
  end

  def edit
  	@article = Article.find(params[:id])
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)

	if @article.valid?
    @article.user_id = @logged_in_user.id

		@article.save

		redirect_to @article
	else
		render "new"
	end
  end

  def update
	  @article = Article.find(params[:id])

  	@article.update(article_params)

	if @article.valid?
		@article.save

		redirect_to @article
	else
		render "edit"
	end
  end

  def destroy
      @article = Article.find(params[:id])
      @article.destroy
 
      redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
  	
    if !@article.votes.exists?(:user_id => @voter.id)
        @article.votes.create(:user_id => @voter.id)
    end

    redirect_to @article
  end

  def destroy
	@article = Article.find(params[:article_id])

    @vote = Vote.find_by_article_id_and_user_id(params[:article_id], params[:id])
  	
    @vote.destroy

    redirect_to @article
  end

  private
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<ul>
	<% @article.errors.full_messages.each do |msg| %>
  		<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %><br />
  </div>
    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, cols: 50, rows: 10, class: "form-control" %><br />
  </div>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/articles/edit.html.erb
<% content_for :header do %>
	<h1>Edit Article</h1>
	<p><%= @article.title %></p>
<% end %>

<% content_for :content do %>
	<%= render 'form' %>
<% end %>

app/views/articles/index.html.erb
<% content_for :header do %>
	<h1>Articles List</h1>
<% end %>

<% content_for :content do %>
	<p><%= link_to "New Article", new_article_path, :class => "btn btn-default" %></p>
	<table class="table table-striped">
  		<thead>
  			<tr>
  				<th>Title</th>
  				<th>Blurb</th>
  				<th width="220">Actions</th>
  			</tr>
  		</thead>
  		<tbody>
  			<% @articles.each do |article| %>
			<tr>
				<td><%= article.title %></td>
				<td><%= article.blurb %></td>
				<td>
					<ul class="actions">
						<li><%= link_to "Show Details", article_path(article), :class => "btn btn-default" %></li>
						<li><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %></li>
					</ul>
				</td>
			</tr>
			<% end %>
  		</tbody>
	</table>
<% end %>

app/views/articles/new.html.erb
<% content_for :header do %>
	<h1>New Article</h1>
<% end %>

<% content_for :content do %>
	<%= render 'form' %>
<% end %>

app/views/articles/show.html.erb
<% content_for :header do %>
	<h1>Title</h1>
	<p><%= @article.title %></p>
<% end %>

<% content_for :content do %>
	<h1>Blurb</h1>
	<p><%= @article.blurb %></p>

	<h1>Description</h1>
	<p><%= @article.description %></p>

	<h1>Author</h1>
	<p><%= @article.user.name %></p>

	<h1>Votes</h1>
	<p><%= @article.votes.length %></p>

	<hr>

	<ul class="actions">
		<% if !@article.votes.exists?(:user_id => @voter.id) and @allowed_voting_groups.include? @voter.group %>
			<li><%= link_to "Vote", article_votes_path(@article), method: :post, :class => 'btn btn-default' %></li>
		<% else %>
			<li><%= link_to "Unvote", article_vote_path(@article, @voter), method: :delete, :class => 'btn btn-default' %></li>
		<% end %>	
		<li><%= link_to "Show all", articles_path, :class => 'btn btn-default' %></li>
		<li><%= link_to "Edit", edit_article_path(@article), :class => 'btn btn-default' %></li>
		<li><%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default' %></li>
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Railsgirls</title>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Articles", articles_path %></li>
            </ul>
            <p class="navbar-text navbar-right">Signed in as <a href="#" class="navbar-link"><%=@voter.name %></a></p>
        </div>
    </nav>
	<div class="row header">
		<div class="col-md-12">
			<%= yield(:header) %>
		</div>
	</div>
	<div class="row content">
		<div class="col-md-12">
			<%= yield(:content) %>
		</div>
	</div>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<% content_for :header do %>
	<h1>Hello</h1>
<% end %>